---
# plugin installation tasks for ansible-role-vim.

- name: Clone {{ plugin_data.type }} plugins into place.
  git:
    clone: true
    dest: "{{ vim_plugin_parent_directory }}/{{ plugin_data.directory }}/{{ (plugin.repo | basename | splitext)[0] }}"
    # When updating, do so even if there are local changes to the repo (this
    # happens when we generate helptags for Vim).
    force: true
    repo: "{{ plugin.repo }}"
    # Update when needed (in practice, this will happen only when 'version' is
    # set to 'master' or 'HEAD').
    update: true
    version: "{{ plugin.version | default('HEAD') }}"
  loop: "{{ plugin_data.list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest

- name: Create/update helptags for {{ plugin_data.type }} plugins.
  shell: |
    if [ -d doc ]; then
      cd doc && vim -c 'helptags .' -c q
    fi
  args:
    chdir: "{{ vim_plugin_parent_directory }}/{{ plugin_data.directory }}/{{ (plugin.repo | basename | splitext)[0] }}"
  loop: "{{ plugin_data.list }}"
  loop_control:
    loop_var: plugin
  tags:
    - molecule-idempotence-notest
